[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "apps/web/.next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../apps/web/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[functions]
  directory = "apps/api/netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@solana/web3.js", "@jup-ag/core"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
